// auth, navigation
export const RESTORE_SESSION = 'RESTORE_SESSION';
export const RESTORE_SESSION_REQUEST = 'RESTORE_SESSION_REQUEST';
export const RESTORE_SESSION_SUCCESS = 'RESTORE_SESSION_SUCCESS';
export const RESTORE_SESSION_FAILED = 'RESTORE_SESSION_FAILED';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SIGNIN_WITH_EMAIL = 'SIGNIN_WITH_EMAIL';
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILED = 'SIGNOUT_FAILED';

export const LOGIN_WORDPRESS = 'LOGIN_WORDPRESS';
export const LOGIN_WORDPRESS_REQUEST = 'LOGIN_WORDPRESS_REQUEST';
export const LOGIN_WORDPRESS_SUCCESS = 'LOGIN_WORDPRESS_SUCCESS';
export const LOGIN_WORDPRESS_FAILED = 'LOGIN_WORDPRESS_FAILED';

// navigation
export const SHOW_CAMERA_SCREEN = 'SHOW_CAMERA_SCREEN';

// book
export const CLEAR_BOOKDATA = 'CLEAR_BOOKDATA';
export const CLEAR_SUMMARY = 'CLEAR_SUMMARY';

export const FETCH_BOOKDATA = 'FETCH_BOOKDATA';
export const FETCH_BOOKDATA_REQUEST = 'FETCH_BOOKDATA_REQUEST';
export const FETCH_BOOKDATA_SUCCESS = 'FETCH_BOOKDATA_SUCCESS';
export const FETCH_BOOKDATA_FAILED = 'FETCH_BOOKDATA_FAILED';

export const DELETE_BOOKDATA = 'DELETE_BOOKDATA';

export const UPLOAD_BOOKDATA = 'UPLOAD_BOOKDATA';
export const UPLOAD_BOOKDATA_REQUEST = 'UPLOAD_BOOKDATA_REQUEST';
export const UPLOAD_BOOKDATA_SUCCESS = 'UPLOAD_BOOKDATA_SUCCESS';
export const UPLOAD_BOOKDATA_FAILED = 'UPLOAD_BOOKDATA_FAILED';
